# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 22:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportWaiting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waiting_lat', models.FloatField(default=-1.0, max_length=20)),
                ('waiting_lon', models.FloatField(default=-1.0, max_length=20)),
                ('waiting_num', models.CharField(max_length=20)),
                ('remark_text', models.CharField(default=None, max_length=200)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('still_waiting', models.BooleanField(default=True)),
            ],
        ),
    ]
